const bankAccounts = [
  {
    institutionName: 'TD Bank',
    accountId: 'gGqEMkVopPFEWjZlQknKcpWPPLgkEeiLXKr8W',
    currentBalance: 110,
    availableBalance: 100,
    currency: 'USD',
    maskedAccountNumber: '0000',
    accountName: 'Plaid Checking',
    officialAccountName: 'Plaid Gold Standard 0% Interest Checking',
    accountType: 'depository',
    accountSubType: 'checking',
  },
  {
    institutionName: 'TD Bank',
    accountId: '8dXNJqGg6Dfwg7qjbeJAtBMAA64DlXiZy9z3G',
    currentBalance: 210,
    availableBalance: 200,
    currency: 'USD',
    maskedAccountNumber: '1111',
    accountName: 'Plaid Saving',
    officialAccountName: 'Plaid Silver Standard 0.1% Interest Saving',
    accountType: 'depository',
    accountSubType: 'savings',
  },
  {
    institutionName: 'TD Bank',
    accountId: 'EpX8Vv4J7wikXB9d3nx8uNkrrn8dVjCgLoVxP',
    currentBalance: 1000,
    currency: 'USD',
    maskedAccountNumber: '2222',
    accountName: 'Plaid CD',
    officialAccountName: 'Plaid Bronze Standard 0.2% Interest CD',
    accountType: 'depository',
    accountSubType: 'cd',
  },
  {
    institutionName: 'TD Bank',
    accountId: 'W7naXzG3JLfkPZNlyExWuZn33LkaDXuPGpvZK',
    currentBalance: 410,
    limit: 2000,
    currency: 'USD',
    maskedAccountNumber: '3333',
    accountName: 'Plaid Credit Card',
    officialAccountName: 'Plaid Diamond 12.5% APR Interest Credit Card',
    accountType: 'credit',
    accountSubType: 'credit card',
  },
  {
    institutionName: 'TD Bank',
    accountId: 'AZXLwp3J1xFKGx9LDnreFmr77Jvz4gF4vgyrA',
    currentBalance: 43200,
    availableBalance: 43200,
    currency: 'USD',
    maskedAccountNumber: '4444',
    accountName: 'Plaid Money Market',
    officialAccountName: 'Plaid Platinum Standard 1.85% Interest Money Market',
    accountType: 'depository',
    accountSubType: 'money market',
  },
  {
    institutionName: 'TD Bank',
    accountId: 'GgXWnoPJwyIKgnqyvx9EFd7PPlbjVXcG4b8M3',
    currentBalance: 320.76,
    currency: 'USD',
    maskedAccountNumber: '5555',
    accountName: 'Plaid IRA',
    accountType: 'investment',
    accountSubType: 'ira',
  },
  {
    institutionName: 'TD Bank',
    accountId: 'nGdyRwVv4MFGMLZNe6yqtwbEEAxNB9F3BzElQ',
    currentBalance: 23631.9805,
    currency: 'USD',
    maskedAccountNumber: '6666',
    accountName: 'Plaid 401k',
    accountType: 'investment',
    accountSubType: '401k',
  },
  {
    institutionName: 'TD Bank',
    accountId: 'bGnLDgVZp6FGLdpmX3Egtp7KKBrADWiowWzb6',
    currentBalance: 65262,
    currency: 'USD',
    maskedAccountNumber: '7777',
    accountName: 'Plaid Student Loan',
    accountType: 'loan',
    accountSubType: 'student',
  },
  {
    institutionName: 'TD Bank',
    accountId: 'mGxmMbVvJgFEe18mpDolceENN7vn58F451Pye',
    currentBalance: 56302.06,
    currency: 'USD',
    maskedAccountNumber: '8888',
    accountName: 'Plaid Mortgage',
    accountType: 'loan',
    accountSubType: 'mortgage',
  },
  {
    institutionName: 'RBC Royal Bank',
    accountId: '6Ggk15Bz6ofyZbJkx77zFve4wEJDKACbGM4EA',
    currentBalance: 110,
    availableBalance: 100,
    currency: 'CAD',
    maskedAccountNumber: '0000',
    accountName: 'Plaid Checking',
    officialAccountName: 'Plaid Gold Standard 0% Interest Checking',
    accountType: 'depository',
    accountSubType: 'checking',
  },
  {
    institutionName: 'RBC Royal Bank',
    accountId: 'XA83D6waGzfKEAQ4r55vCkwovrlP1NuPyzG7z',
    currentBalance: 210,
    availableBalance: 200,
    currency: 'CAD',
    maskedAccountNumber: '1111',
    accountName: 'Plaid Saving',
    officialAccountName: 'Plaid Silver Standard 0.1% Interest Saving',
    accountType: 'depository',
    accountSubType: 'savings',
  },
];

const institutionNames = bankAccounts.map(({ institutionName }) => institutionName);
const uniqueBankAccounts = new Set(institutionNames);
const diffAccounts = {};
uniqueBankAccounts.forEach((institutionName) => {
  diffAccounts[institutionName] = bankAccounts.filter(
    ({ institutionName: internalInstitutionName }) => internalInstitutionName === institutionName,
  );
});
console.log('institutionNames', institutionNames);
console.log('uniqueBankAccounts', uniqueBankAccounts);
console.log('diffAccounts', diffAccounts);
