/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
import { RailzVisualizationsConfiguration, RailzVisualizationsFilter, RailzVisualizationsOptions } from "./components/railz-visualizations/types";
export namespace Components {
    interface RailzVisualizations {
        "configuration": RailzVisualizationsConfiguration | string;
        "filter": RailzVisualizationsFilter | string;
        "options": RailzVisualizationsOptions | string;
    }
}
declare global {
    interface HTMLRailzVisualizationsElement extends Components.RailzVisualizations, HTMLStencilElement {
    }
    var HTMLRailzVisualizationsElement: {
        prototype: HTMLRailzVisualizationsElement;
        new (): HTMLRailzVisualizationsElement;
    };
    interface HTMLElementTagNameMap {
        "railz-visualizations": HTMLRailzVisualizationsElement;
    }
}
declare namespace LocalJSX {
    interface RailzVisualizations {
        "configuration": RailzVisualizationsConfiguration | string;
        "filter": RailzVisualizationsFilter | string;
        "options"?: RailzVisualizationsOptions | string;
    }
    interface IntrinsicElements {
        "railz-visualizations": RailzVisualizations;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "railz-visualizations": LocalJSX.RailzVisualizations & JSXBase.HTMLAttributes<HTMLRailzVisualizationsElement>;
        }
    }
}
