# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Tests

on:
  pull_request:
    types: [opened, synchronize]

jobs:
  test:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [16.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/
    steps:
      - name: Use Node.js ${{ matrix.node-vQersion }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}
      - uses: actions/checkout@v2
      - uses: borales/actions-yarn@v2.1.0
        with:
          cmd: install
      - uses: borales/actions-yarn@v2.1.0
        with:
          cmd: build
      - uses: borales/actions-yarn@v2.1.0
        with:
          cmd: test
